coordinator=true
node-scheduler.include-coordinator=true
http-server.http.port=8080
discovery.uri=http://starburst:8080

query.max-memory=4GB
query.max-total-memory=4GB

http-server.https.enabled=true
http-server.https.port=8443
http-server.https.keystore.path=/certs/trino.p12
http-server.https.keystore.key=123abc
