connector.name=delta-lake
hive.metastore.uri=thrift://hive:9083

fs.native-s3.enabled=true

s3.endpoint=https://minio.edupia.com.vn:9005
s3.aws-access-key=RANNKz5iDjCjwuSMERHG
s3.aws-secret-key=s09X8CONsQAX317NxP9txW05rRXayv3jjtxFe6Vv
s3.path-style-access=true
s3.region=us-east-1

delta.enable-non-concurrent-writes=true