connector.name=delta_lake
hive.metastore.uri=thrift://hive:9083
fs.native-s3.enabled=true

s3.endpoint=https://minio.edupia.com.vn:9005
s3.region=us-east-1
s3.max-connections=500
s3.connection-max-idle-time=1h
s3.aws-access-key=RANNKz5iDjCjwuSMERHG
s3.aws-secret-key=s09X8CONsQAX317NxP9txW05rRXayv3jjtxFe6Vv
s3.path-style-access=true


delta.metadata.cache-ttl=30m
delta.enable-non-concurrent-writes=true
delta.metadata.cache-max-retained-size=64MB
delta.compression-codec=GZIP
delta.max-partitions-per-writer=100
delta.idle-writer-min-file-size=16MB
delta.default-checkpoint-writing-interval=10
delta.checkpoint-row-statistics-writing.enabled=true
delta.hive-catalog-name=hive


